apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-monitoring
  labels:
    app: cloud-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-monitoring
  template:
    metadata:
      labels:
        app: cloud-monitoring
    spec:
      containers:
      - name: cloud-monitoring-container
        image: mousumidey/flask-app:latest
        ports:
        - containerPort: 5000
